### ISSUE TITLE
부착할 서비스 리스트

### ISSUE THREAD

**Issue by hyesungoh** [dogVelopers/dogVelopers#1]
사용자 모니터링, 이슈 트래킹 등을 위해 부착할 서비스 리스트

- [x] GA
- [x] Sentry
- [x] Hotjar

**Comment by eastheat10** [comment]
[GA](https://analytics.google.com/analytics/web/#/)
[Hotjar](https://insights.hotjar.com/sites/2816776/dashboard?token=ecb61a100c424abc94169829bb89f6df&utm_source=invite&utm_medium=email&utm_campaign=teaminvite)[https://insights.hotjar.com/sites/2816776/dashboard?token=ecb61a100c424abc94169829bb89f6df&utm_source=invite&utm_medium=email&utm_campaign=teaminvite](https://insights.hotjar.com/sites/2816776/dashboard?token=ecb61a100c424abc94169829bb89f6df&utm_source=invite&utm_medium=email&utm_campaign=teaminvite)

backend는 log4j 사용하겠습니다.
